version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  trainer-api:
    build: .
    container_name: trainer-api
    ports:
      - "50051:50051"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=TrainerDB
      - TRAINERS_COLLECTION=trainers

volumes:
  mongo_data:
